# Generated by Django 4.1.4 on 2023-01-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('desig', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('fb_link', models.URLField(max_length=300)),
                ('twitter_link', models.URLField(max_length=120)),
                ('g_link', models.URLField(max_length=120)),
            ],
        ),
    ]
